name: CI/CD Pipeline for Backend & Frontend

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        run: npm install
        working-directory: ./Backend

      - name: Run Backend Tests
        run: npm test
        working-directory: ./Backend

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./my-react-app

      - name: Run Frontend Tests
        run: npm test
        working-directory: ./my-react-app
